---
title: "Proficiency Test 2"
author: "Ashay Joshi"
format: pdf
editor: visual
---

## Task 1

```{r}
for(x in mtcars$mpg[1:3]) {
  print(x)
}

```
## Task 2

```{r}
count_above <- function(numeric_vector, cuttoff_value) { # creates the function with numeric_vector and cuttoff_value as arguments
  count <- 0 # sets the initial count to 0
  
  for (i in 1:length(numeric_vector)) { # creates a for loop to iterate through the vector
    if (numeric_vector[i] > cuttoff_value) { # this is a selection statement to see whether the cuttoff value is greater than a certain number in the vector
      count <- count +1 # adds 1 to the count if the observation is greater than the cutoff value 
    }
}
  return(count) # returns the count 
}

```
```{r}
count_above(iris$Sepal.Length, 6)
```


```{r}
count_above(mtcars$disp,150)
```

## Task 3

Making functions essentially means that certain functions will perform different tasks when in the presence of certain packages. For example when the dplyr function is present, some of the functions in base R will not perform the same tasks, because the package defines those same functions differently. 
